language: python
python:
  - "2.7"
install: 
  - pip install -r test_requirements.txt --use-mirrors
  - pip install coveralls
script:
  - cd db_obfuscate/tests
  - ./runtests.py
  - mv .coverage ../../
  - cd ../../
after_success: 
  - coveralls
